### ISSUE TITLE
Looks like using the new 'Additional Images' feature destroys the cookie information for the site itself.

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#9] opened 2023-09-20 20:21 UTC
Not sure, but it seems to be more than coincidence. The first time I played with adding additional images, I got logged out on F95Zone in my browser. 
At first, I thought it was a fluke, but it has never happened before. I'm always logged on and always have tabs open on the site (I rarely close my browser, OperaGX)

But it happened again just now. I closed F95CheckerX because I encountered an `invalid banner` again and wanted to examine the downloaded image (always ends up with an `. img` extension.
The moment I closed F95CheckerX and opened the thread ([Avalon](https://f95zone.to/threads/avalon-v8-2-lockheart.44397/)) I got a logged out view. 

It looks like it happens when closing F95CheckerX, as I can still browse the forum while F95CheckerX is open.
I just tried it a couple of times, and in the few times I tried, I only got logged out once but, the later attempts I only tried it on one thread each time.

Still, it feels like more than coincidence, as I have never ever have gotten auto-logged off before.

**Comment by littleraisins** [comment] 2023-09-20 20:37
> But it happened again just now. I closed F95CheckerX because I encountered an invalid banner again and wanted to examine the downloaded image (always ends up with an . img extension.

This whole invalid banner thing was resolved by recent commit, and I opened a PR in F95Checker repo. It's not the cause.

New features can't remove cookies or in any way alter them.
My guess here, if it's not a coincidence of course - you are getting kicked out because of making too many requests (downloading thread screenshots). Maybe. I'm not sure it's possible, but this is the only thing I can think of.

Need more testing.

**Comment by FaceCrap** [comment] 2023-09-21 19:41
It seems strange getting booted for downloading thread images. If it were that, I would expect the connection from F95CheckerX to experience the same problem as my browser while accessing the forum. 

The weird thing is, why didn't it happen while F95CheckerX was running, but only after it closed...

I'll try again this weekend and see what happens

**Comment by FaceCrap** [comment] 2023-09-24 12:05
Close this one, it looks like it is pure coincidence. I also got logged off doing something with thread images through a totally different route. It's something on the forum side that decides you need to be kicked, doesn't matter where the trigger originates,

**Closed** 2023-09-24 12:07 UTC

**Comment by littleraisins** [comment] 2023-09-24 13:28
During development, I've downloaded a bunch of them, and even more after release, never lost my auth. Weird.
